### ISSUE TITLE
Installation of SpeedSeq by git error!

### ISSUE THREAD

**Issue by wangshun1121** [hall-lab/speedseq#100]
I try to install SpeedSeq by "git clone" and make, but some of the folders in "./speedseq/src" are empty, such as parallel, samblaster etc.
I wonder if some dependant tools have been modified, and would you please check all these tools? @cc2qe

**Comment by wenty-qq** [comment]
I met the same problem. Please refer to this page "https://github.com/hall-lab/speedseq/issues/42".

**Comment by cc2qe** [comment]
Duplicate of https://github.com/hall-lab/speedseq/issues/42
