### ISSUE TITLE
Speedseq somatic - slow speed

### ISSUE THREAD

**Issue by iranmdl** [hall-lab/speedseq#101]
Hi there,
I'm trying `speedseq somatic` analysis on my tumor/normal paired subset. I was wondering if I'm missing any parameter or argument because I've observed a extremely slow speed in the analysis.

This is my **command**:

`speedseq somatic -o tumor_1 -t 4 -C 2 -F 0.02 -w region.bed /shared/reference/seq/GRCh37.fa normal_1_sorted_dedup_mapped_recab_realigned.bam tumor_1_sorted_dedup_mapped_recab_realigned.bam`

> ###### Elapsed time: 10h 07m 03s

The size of the input bams:

```
tumor_1_sorted_dedup_mapped_recab_realigned.bam --> 229M (1585801 alignments)
normal_1_sorted_dedup_mapped_recab_realigned.bam --> 228M (1586210 alignments)
```

Is this timing normal?
Thank you in advance,
Irantzu

**Comment by cc2qe** [comment]
That seems fairly slow. Is this WGS data? You can try adding more threads (timings for the paper were done using 32 threads)

**Comment by iranmdl** [comment]
Of course if I add more threads I would expect the time to be reduced but I was just wondering why is too slow. I'm using other tools like `VarScan` and `MuTect` and the timing for them is 3minutes each while 10h are needed for `speedseq`. The reads are WES data, specifically a subset of reads of DREAM challenge 3 dataset.

**Comment by cc2qe** [comment]
If it's exome, perhaps try it without `-w region.bed`. Those regions were designed for WGS, and if your BAMs are extremely deep coverage over short exons then spooling up so many jobs may be inefficient

**Comment by iranmdl** [comment]
Yes, that was the problem :)
Thank you very much!
