### ISSUE TITLE
Error: when install Variant Effect Predictor

### ISSUE THREAD

**Issue by jianzuoyi** [hall-lab/speedseq#107]
I installed the Variant Effect Predictor as follows (This instructions were shown in the home page of SpeedSeq):

curl -OL https://github.com/Ensembl/ensembl-tools/archive/release/76.zip
unzip 76.zip
perl ensembl-tools-release-76/scripts/variant_effect_predictor/INSTALL.pl \
	-c $SPEEDSEQ_DIR/annotations/vep_cache \
	-a ac -s homo_sapiens -y GRCh37

cp ensembl-tools-release-76/scripts/variant_effect_predictor/variant_effect_predictor.pl $SPEEDSEQ_DIR/bin
cp -r Bio $SPEEDSEQ_DIR/bin

# Update the VEP and VEP_CACHE_DIR variables in speedseq.config to point to
# $SPEEDSEQ_DIR/bin/variant_effect_predictor.pl and $SPEEDSEQ_DIR/annotations/vep_cache

But the 'INSTALL.pl ' has some errors when I run this command:
perl ensembl-tools-release-76/scripts/variant_effect_predictor/INSTALL.pl \
	-c $SPEEDSEQ_DIR/annotations/vep_cache \
	-a ac -s homo_sapiens -y GRCh37'

I found that the 'INSTALL.pl' script need 'BioPerl-1.6.1.tar.gz', but the url 'http://bioperl.org/DIST/BioPerl-1.6.1.tar.gz' is not exist.The installation of VEP failed.

Any solutions for this problem? thank you very much.

**Comment by cc2qe** [comment]
It looks like bioperl has changed their installation procedure. I'd recommended referring to the [VEP installation page](http://www.ensembl.org/info/docs/tools/vep/script/vep_download.html) and running the installation commands there:
```
curl -L -O https://github.com/Ensembl/ensembl-vep/archive/release/88.zip
unzip 88.zip
cd ensembl-vep-release-88/
```
followed by:
```
perl ensembl-vep-release-88/INSTALL.pl \
    -c $SPEEDSEQ_DIR/annotations/vep_cache \
    -a ac -s homo_sapiens -y GRCh37
```

**Comment by jianzuoyi** [comment]
Thanks very much for your answer. My problems is solved, and I'm going to close this issue.
