### ISSUE TITLE
Speedseq Sv on exome data

### ISSUE THREAD

**Issue by silenus092** [hall-lab/speedseq#109]
Hi 
I run SV by using the following command 

`speedseq sv -t 8 -o /mnt/speedSeq_data/SR03/SR03 -x /opt/speedseq/annotations/ceph18.b37.lumpy.exclude.2014-01-15.bed -g -d -B /mnt/speedSeq_data/SR03/SR03.bam -D /mnt/speedSeq_data/SR03/SR03.discordants.bam -S /mnt/speedSeq_data/SR03/SR03.splitters.bam -R /mnt/speedSeq_data/RefGRch37/human_g1k_v37.fasta -K /opt/speedseq/bin/speedseq.config  -T /mnt/speedSeq_data/tmp/`

And then speedseq generated error log as below;

Can't open file '/mnt/speedSeq_data/tmp//cnvnator-temp/SR03.bam.hist.root'.
Error in <TFile::TFile>: file /mnt/speedSeq_data/tmp//cnvnator-temp/SR03.bam.hist.root does not exist
Can't open file '/mnt/speedSeq_data/tmp//cnvnator-temp/SR03.bam.hist.root'.
Error in <TFile::TFile>: file /mnt/speedSeq_data/tmp//cnvnator-temp/SR03.bam.hist.root does not exist
Can't open file '/mnt/speedSeq_data/tmp//cnvnator-temp/SR03.bam.hist.root'.
Error in <TFile::TFile>: file /mnt/speedSeq_data/tmp//cnvnator-temp/SR03.bam.hist.root does not exist
Can't open file '/mnt/speedSeq_data/tmp//cnvnator-temp/SR03.bam.hist.root'.
Error in <TFile::TFile>: file /mnt/speedSeq_data/tmp//cnvnator-temp/SR03.bam.hist.root does not exist
Can't open file '/mnt/speedSeq_data/tmp//cnvnator-temp/SR03.bam.hist.root'.
Can't find all necessary histograms for chromosome '22' in file /mnt/speedSeq_data/tmp//cnvnator-temp/SR03.bam.hist.root.
Error in <TFile::TFile>: file /mnt/speedSeq_data/tmp//cnvnator-temp/SR03.bam.hist.root does not exist
Can't open file '/mnt/speedSeq_data/tmp//cnvnator-temp/SR03.bam.hist.root'.
Error in <TFile::TFile>: file /mnt/speedSeq_data/tmp//cnvnator-temp/SR03.bam.hist.root does not exist
Can't open file '/mnt/speedSeq_data/tmp//cnvnator-temp/SR03.bam.hist.root'.
Error in <TFile::TFile>: file /mnt/speedSeq_data/tmp//cnvnator-temp/SR03.bam.hist.root does not exist
Can't open file '/mnt/speedSeq_data/tmp//cnvnator-temp/SR03.bam.hist.root'.
Error in <TFile::TFile>: file /mnt/speedSeq_data/tmp//cnvnator-temp/SR03.bam.hist.root does not exist
Can't open file '/mnt/speedSeq_data/tmp//cnvnator-temp/SR03.bam.hist.root'.
Error in <TFile::TFile>: file /mnt/speedSeq_data/tmp//cnvnator-temp/SR03.bam.hist.root does not exist
Can't open file '/mnt/speedSeq_data/tmp//cnvnator-temp/SR03.bam.hist.root'.
Can't find all necessary histograms for chromosome '22' in file /mnt/speedSeq_data/tmp//cnvnator-temp/SR03.bam.hist.root.
Error in <TFile::TFile>: file /mnt/speedSeq_data/tmp//cnvnator-temp/SR03.bam.hist.root does not exist
Can't open file '/mnt/speedSeq_data/tmp//cnvnator-temp/SR03.bam.hist.root'.
Error in <TFile::TFile>: file /mnt/speedSeq_data/tmp//cnvnator-temp/SR03.bam.hist.root does not exist
Can't open file '/mnt/speedSeq_data/tmp//cnvnator-temp/SR03.bam.hist.root'.
Error in <TFile::TFile>: file /mnt/speedSeq_data/tmp//cnvnator-temp/SR03.bam.hist.root does not exist
Can't open file '/mnt/speedSeq_data/tmp//cnvnator-temp/SR03.bam.hist.root'.
Error in <TFile::TFile>: file /mnt/speedSeq_data/tmp//cnvnator-temp/SR03.bam.hist.root does not exist
Can't open file '/mnt/speedSeq_data/tmp//cnvnator-temp/SR03.bam.hist.root'.
Error in <TFile::TFile>: file /mnt/speedSeq_data/tmp//cnvnator-temp/SR03.bam.hist.root does not exist
Can't open file '/mnt/speedSeq_data/tmp//cnvnator-temp/SR03.bam.hist.root'.
Can't find all necessary histograms for chromosome '22' in file /mnt/speedSeq_data/tmp//cnvnator-temp/SR03.bam.hist.root.
Traceback (most recent call last):
  File "/opt/speedseq//bin/annotate_rd.py", line 350, in <module>
    sys.exit(main())
  File "/opt/speedseq//bin/annotate_rd.py", line 342, in main
    sv_readdepth(args.input_vcf, args.sample, args.root, args.window, args.output_vcf, args.debug, args.cnvnator)
  File "/opt/speedseq//bin/annotate_rd.py", line 321, in sv_readdepth
    var.genotype(sample).set_format('CN', cn_list[i])
IndexError: list index out of range

Thanks,
Note

**Comment by cc2qe** [comment]
SpeedSeq is intended for WGS data, not exome data. While some of the modules are adaptable to exome sequence, the SV modules will not work.

**Comment by silenus092** [comment]
Thank you very much 

again , I used WGS data instead , and called SV same command above.The speedseq generated error log as below;

> Error in <TFile::TFile>: file /mnt/speedSeq_data/tmp/cnvnator-temp/C747.bam.hist.root does not exist
Can't open file '/mnt/speedSeq_data/tmp/cnvnator-temp/C747.bam.hist.root'.
Error in <TFile::TFile>: file /mnt/speedSeq_data/tmp/cnvnator-temp/C747.bam.hist.root does not exist
Can't open file '/mnt/speedSeq_data/tmp/cnvnator-temp/C747.bam.hist.root'.
Error in <TFile::TFile>: file /mnt/speedSeq_data/tmp/cnvnator-temp/C747.bam.hist.root does not exist
Can't open file '/mnt/speedSeq_data/tmp/cnvnator-temp/C747.bam.hist.root'.
Error in <TFile::TFile>: file /mnt/speedSeq_data/tmp/cnvnator-temp/C747.bam.hist.root does not exist
Can't open file '/mnt/speedSeq_data/tmp/cnvnator-temp/C747.bam.hist.root'.
Error in <TFile::TFile>: file /mnt/speedSeq_data/tmp/cnvnator-temp/C747.bam.hist.root does not exist
Can't open file '/mnt/speedSeq_data/tmp/cnvnator-temp/C747.bam.hist.root'.
Can't find all necessary histograms for chromosome 'GL000219.1' in file /mnt/speedSeq_data/tmp/cnvnator-temp/C747.bam.hist.root.
Error in <TFile::TFile>: file /mnt/speedSeq_data/tmp/cnvnator-temp/C747.bam.hist.root does not exist
Can't open file '/mnt/speedSeq_data/tmp/cnvnator-temp/C747.bam.hist.root'.
Error in <TFile::TFile>: file /mnt/speedSeq_data/tmp/cnvnator-temp/C747.bam.hist.root does not exist
Can't open file '/mnt/speedSeq_data/tmp/cnvnator-temp/C747.bam.hist.root'.
Error in <TFile::TFile>: file /mnt/speedSeq_data/tmp/cnvnator-temp/C747.bam.hist.root does not exist
Can't open file '/mnt/speedSeq_data/tmp/cnvnator-temp/C747.bam.hist.root'.
Error in <TFile::TFile>: file /mnt/speedSeq_data/tmp/cnvnator-temp/C747.bam.hist.root does not exist
Can't open file '/mnt/speedSeq_data/tmp/cnvnator-temp/C747.bam.hist.root'.
Error in <TFile::TFile>: file /mnt/speedSeq_data/tmp/cnvnator-temp/C747.bam.hist.root does not exist
Can't open file '/mnt/speedSeq_data/tmp/cnvnator-temp/C747.bam.hist.root'.
Can't find all necessary histograms for chromosome 'GL000224.1' in file /mnt/speedSeq_data/tmp/cnvnator-temp/C747.bam.hist.root.
Error in <TFile::TFile>: file /mnt/speedSeq_data/tmp/cnvnator-temp/C747.bam.hist.root does not exist
Can't open file '/mnt/speedSeq_data/tmp/cnvnator-temp/C747.bam.hist.root'.
Error in <TFile::TFile>: file /mnt/speedSeq_data/tmp/cnvnator-temp/C747.bam.hist.root does not exist
Can't open file '/mnt/speedSeq_data/tmp/cnvnator-temp/C747.bam.hist.root'.
Error in <TFile::TFile>: file /mnt/speedSeq_data/tmp/cnvnator-temp/C747.bam.hist.root does not exist
Can't open file '/mnt/speedSeq_data/tmp/cnvnator-temp/C747.bam.hist.root'.
Error in <TFile::TFile>: file /mnt/speedSeq_data/tmp/cnvnator-temp/C747.bam.hist.root does not exist
Can't open file '/mnt/speedSeq_data/tmp/cnvnator-temp/C747.bam.hist.root'.
Error in <TFile::TFile>: file /mnt/speedSeq_data/tmp/cnvnator-temp/C747.bam.hist.root does not exist
Can't open file '/mnt/speedSeq_data/tmp/cnvnator-temp/C747.bam.hist.root'.
Can't find all necessary histograms for chromosome 'GL000224.1' in file /mnt/speedSeq_data/tmp/cnvnator-temp/C747.bam.hist.root.
Traceback (most recent call last):
  File "/opt/speedseq//bin/annotate_rd.py", line 350, in <module>
    sys.exit(main())
  File "/opt/speedseq//bin/annotate_rd.py", line 342, in main
    sv_readdepth(args.input_vcf, args.sample, args.root, args.window, args.output_vcf, args.debug, args.cnvnator)
  File "/opt/speedseq//bin/annotate_rd.py", line 321, in sv_readdepth
    var.genotype(sample).set_format('CN', cn_list[i])
IndexError: list index out of range

Moreover , any recommend  for SV annotation ?

Many thanks,
Note
