### ISSUE TITLE
bamtofastq error

### ISSUE THREAD

**Issue by crazyhottommy** [hall-lab/speedseq#30]
Hi there,

I am sorry to bother you again. The `speedseq realign` was working for me, but when the HPC staff re-install it, I had a problem with the bamtofastq python script. Can you tell what's wrong here? Thank you! Note, it is the same bam file (which was successfully remapped)  that gives me error. My bam file should contain the cigar information for the reads.

Ming 

Traceback (most recent call last):
  File "/risapps/src6/speedseq//bin/bamtofastq.py", line 157, in <module>
    sys.exit(main())
  File "/risapps/src6/speedseq//bin/bamtofastq.py", line 153, in main
    args.header)
  File "/risapps/src6/speedseq//bin/bamtofastq.py", line 64, in bamtofastq
    if 5 in [x[0] for x in al.cigar]:
TypeError: 'NoneType' object is not iterable
samblaster: Version 0.1.21
samblaster: Inputting from stdin
samblaster: Outputting to stdout
samblaster: Opening temp/disc_pipe for write.
samblaster: Opening temp/spl_pipe for write.
[gzclose] buffer error
samblaster: Loaded 84 header sequence entries.
Traceback (most recent call last):
  File "/risapps/src6/speedseq//bin/bamtofastq.py", line 157, in <module>
    sys.exit(main())
  File "/risapps/src6/speedseq//bin/bamtofastq.py", line 153, in main
    args.header)
  File "/risapps/src6/speedseq//bin/bamtofastq.py", line 64, in bamtofastq
    if 5 in [x[0] for x in al.cigar]:
TypeError: 'NoneType' object is not iterable

**Comment by cc2qe** [comment]
Hi Ming,

Could you run speedseq realign with the "-v" flag and send the verbose output. Also, if you can send the first 1000 lines of your bam file that would be helpful. My email is cc2qe at virginia dot edu

Thanks,
Colby

**Comment by crazyhottommy** [comment]
Hi Colby,

I was in the ENCODE meeting and just saw you responded. I just sent you the log files and a small bam file to you. 

Thanks for the support for this fast tool!

Ming Tang

**Comment by crazyhottommy** [comment]
in another issue I opened https://github.com/cc2qe/svtyper/issues/12
It looks like the pysam version matters. Your bamtofastq.py also uses pysam, right? Do you think it is a problem here also?

Ming

**Comment by cc2qe** [comment]
Possibly, could you send the output of the following?
```
$ /risapps/rhel6/python/2.7.6/anaconda/bin/python2.7
>>> import pkg_resources
>>> pkg_resources.get_distribution("pysam").version
'0.8.0'
```

**Comment by cc2qe** [comment]
Ok, I am able to realign you BAM file without issue using the following command:
```
speedseq realign -v hs37_ebv.fasta small.bam
```
my guess is that the problem results from the older version of [pysam 0.5](https://github.com/cc2qe/svtyper/issues/12#issuecomment-118422555) that you're using.

Pysam changed the way they handle the [cigar string in 0.7](http://pysam.readthedocs.org/en/latest/release.html#release-0-7). Is there any chance that the HPC staff altered the pysam version since SpeedSeq worked last time?

**Comment by crazyhottommy** [comment]
Updating pysam to 0.8 resolves the problem, but now CNVnator has some errors when I turn on the -d option. It has something to do with the root package. Could you tell what's wrong exactly here?

Warning in <TGMimeTypes::TGMimeTypes>: error opening mime type file /etc/root/root.mimes
Fatal in <TVirtualStreamerInfo::Factory>: Cannot find the plugin handler for TVirtualStreamerInfo! $ROOTSYS/etc/plugins/TVirtualStreamerInfo does not eaborting
Error in <TUnixSystem::StackTrace> script /etc/root/gdb-backtrace.sh is missing

Processing data from the following chromosomes: ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19===== Running tree on input data
Error in tree creation               

Thanks,
Ming

**Comment by cc2qe** [comment]
Seems like ROOT is either improperly installed or you have not run `source /path/to/root/bin/thisroot.sh`

https://root.cern.ch/root/roottalk/roottalk11/1325.html

**Comment by cc2qe** [comment]
I was not able to replicate this error with pysam 0.8.3, but I added a condition to the if statement that hopefully will fix this. let me know if it works
https://github.com/hall-lab/bamkit/commit/be20d77c0902d58fea1c1210af35e79a7ecd2f1f

**Comment by crazyhottommy** [comment]
I let the HPC guy installed pysam0.8.0 for me, and now it works...

**Comment by cc2qe** [comment]
I've heard reports from others via email that https://github.com/hall-lab/speedseq/commit/aa7e66a5877656ea0cf4e05732e991ed366be0f5 resolves this issue, so I'm going to close the ticket. Let me know if there are further problems.
