### ISSUE TITLE
Bam input for alignment

### ISSUE THREAD

**Issue by gpcr** [hall-lab/speedseq#33]
thanks for creating a wonderful tool.
Is there a way to use bam files as input for the alignment step. 
Its very time consuming to generate fastqs (sorting bams and bam2fastx steps) from bams.

**Comment by cc2qe** [comment]
yes, you can use "speedseq realign" to align from BAM files. here's an example command

```
speedseq realign \
    -o sample \
    -M 8 \
    -t 8 \
    -v \
    /gscmnt/gc2719/halllab/genomes/human/GRCh37/hs37_ebv/hs37_ebv.fasta \
    lane1.bam \
    lane2.bam \
    lane3.bam \
    lane4.bam \
    lane5.bam \
    lane6.bam \
    lane7.bam \
    lane8.bam
```

**Comment by gpcr** [comment]
thanks @cc2qe: realign will be very helpful...
My another question: how to call variants in family-aware fashion or it just use combined calling?

**Comment by cc2qe** [comment]
If you have a simple trio, then you can follow these instructions. Otherwise, regular multi-sample calling should be fine, and then you can make a .ped file with family info before loading into GEMINI.
