### ISSUE TITLE
experimental-gls

### ISSUE THREAD

**Issue by gpcr** [hall-lab/speedseq#34]
When running Var module : Getting error messages
"/speedseq/bin/freebayes: unrecognized option '--experimental-gls'
did you mean --use-best-n-alleles ?  " 

Seems "experimental-gls" option is decapitated 

hope it does not effect the outcome?

**Comment by cc2qe** [comment]
I think Erik may have made --experimental-gls default now. However, the version of speedseq packaged in speedseq (freebayes commit [f46d24f](https://github.com/ekg/freebayes/tree/f46d24fa471f8aeaa28d794b452d8c609137e8ea)) still uses experimental-gls, so it should not fail. Is it?

**Comment by gpcr** [comment]
It would be great if we can use the latest tools available...Is it possible to update?

**Comment by cc2qe** [comment]
Updated to freebayes v0.9.21, https://github.com/hall-lab/speedseq/commit/27906e6b725892c61afae309917b9975b8c8aa72
