### ISSUE TITLE
Realign: option to change read groups such as ID and SM

### ISSUE THREAD

**Issue by gpcr** [hall-lab/speedseq#35]
Feature request: option to change read groups such as ID and SM while using realign 

may be implementing using bamaddrg (https://github.com/ekg/bamaddrg) or any of your favorite tool

**Comment by mfoll** [comment]
Similarly, I have some BAM files I want to realign that don't have `@RG` at all... I use `samtools addreplacerg` but it would be easier to be able to do that directly in `speedseq realign`, the same way one can specify the read group header line with `speeds align -R`.
