### ISSUE TITLE
reference is not a tree: 8a570f867dde07fbe9a025f2eec706d44b82966c

### ISSUE THREAD

**Issue by hadoopy** [hall-lab/speedseq#36]
###
git clone --recursive git://github.com/cc2qe/speedseq
…
…
Initialized empty Git repository in /speedseq/src/parallel/.git/
fatal: reference is not a tree: 8a570f867dde07fbe9a025f2eec706d44b82966c
Unable to checkout '8a570f867dde07fbe9a025f2eec706d44b82966c' in submodule path 'src/parallel'
###
Appears the reference is to a commit that’s not been pushed to the main repo

**Comment by cc2qe** [comment]
I can't replicate this on the Wash U cluster, my mac, or an amazon instance. Is there anything about your system that is unique? May also be possible that the [GNU parallel host](http://savannah.gnu.org/git/?group=parallel) was down temporarily.

**Comment by hadoopy** [comment]
Thanks! your are right, the problem is on my side, the git was blocked while https allowed, parallel does not have a https link
