### ISSUE TITLE
What is the difference between speedseq and GATK

### ISSUE THREAD

**Issue by csuliweilong** [hall-lab/speedseq#37]
As we know, GATK HaplotypeCaller is used for SNP calling.
As speedseq is used for SNV calling, what is the difference between these two tools?
Is it possible to use speedseq for SNP calling?

**Comment by cc2qe** [comment]
SNP and SNV are often used interchangeably, although technically SNP only includes polymorphic variants that are common. Both GATK and SpeedSeq do SNV and indel detection. The performance differences between GATK and SpeedSeq (FreeBayes) SNV calling are shown in the paper figure 1b
