### ISSUE TITLE
speedseq sv CNVnator not finding bam file

### ISSUE THREAD

**Issue by s-boardman** [hall-lab/speedseq#40]
I'm testing speedseq on our cluster and am running into an issue where calling speedseq sv with CNVnator doesn't find the bam file passed to it.

The command I'm using is:

```bash
qsub -V -e e_r -o o_r -b Y -cwd -N speedseq_sv_rd \
speedseq sv -R /mnt/lustre/references/hg19/hg19_validated.fa \
-o NA12877 -g -k -d -v \
-B /mnt/archive/analysis/projects/HiSeq/CNV_Genome_Project/External_Data/Illumina_Platinum_Genomes/NA12877/bam_fromfastq_frombam/NA12877.bam \
-S /mnt/archive/analysis/projects/HiSeq/CNV_Genome_Project/External_Data/Illumina_Platinum_Genomes/NA12877/bam_fromfastq_frombam/NA12877.splitters.bam \
-D /mnt/archive/analysis/projects/HiSeq/CNV_Genome_Project/External_Data/Illumina_Platinum_Genomes/NA12877/bam_fromfastq_frombam/NA12877.discordants.bam
```

And the error I receive is:

```python
Traceback (most recent call last):
  File "/opt/gridware/pkg/apps/speedseq/0.0.3a/gcc-4.4.6+root-5.34.30+samtools-0.1.19+python-2.7.3/bin/cnvnator_wrapper.py", line 350, in <module>
    chroms_list = get_chroms_list(args.bam)
  File "/opt/gridware/pkg/apps/speedseq/0.0.3a/gcc-4.4.6+root-5.34.30+samtools-0.1.19+python-2.7.3/bin/cnvnator_wrapper.py", line 153, in get_chroms_list
    proc = subprocess.Popen(['samtools', 'view', '-H', bam_fn], stdout = subprocess.PIPE)
  File "/opt/gridware/pkg/apps/python/2.7.3/gcc-4.4.6/lib/python2.7/subprocess.py", line 679, in __init__
    errread, errwrite)
  File "/opt/gridware/pkg/apps/python/2.7.3/gcc-4.4.6/lib/python2.7/subprocess.py", line 1249, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

And from the verbose output I can see that this is the echoed CNVnator command:

```bash
# run cnvnator-multi
    /opt/gridware/pkg/apps/python/2.7.3/gcc-4.4.6/bin/python2.7 /opt/gridware/pkg/apps/speedseq/0.0.3a/gcc-4.4.6+root-5.34.30+samtools-0.1.19+python-2.7.3/bin/cnvnator_wrapper.py \
--cnvnator /opt/gridware/pkg/apps/speedseq/0.0.3a/gcc-4.4.6+root-5.34.30+samtools-0.1.19+python-2.7.3/bin/cnvnator-multi \
-T NA12877.V0rHAeDGFjgn/cnvnator-temp -t 1 -w 100 \
-b /mnt/archive/analysis/projects/HiSeq/CNV_Genome_Project/External_Data/Illumina_Platinum_Genomes/NA12877/bam_fromfastq_frombam/NA12877.bam \
NA12877.V0rHAeDGFjgn/NA12877.bam.readdepth \
-c /mnt/lustre/references/speedseq/annotations/cnvnator_chroms -g GRCh37
```

Therefore `/mnt/archive/analysis/projects/HiSeq/CNV_Genome_Project/External_Data/Illumina_Platinum_Genomes/NA12877/bam_fromfastq_frombam/NA12877.bam` is args.bam and gives and OSError. However, this file definitely exists and was generated by speedseq align without issue. If I run the speedseq sv command without CNVnator (-d flag) the process completes without errors and I get a genotyped vcf.

Any thoughts/ideas would be greatly appreciated!

**Comment by cc2qe** [comment]
What do the files in ths `/mnt/lustre/references/speedseq/annotations/cnvnator_chroms` directory look like? Do your chromosomes have "chr" prefixes by any chance? SpeedSeq sv currently doesn't support chromosome prefixes because cnvnator's names are rigid, so I'm not sure how it will behave with them.

**Comment by s-boardman** [comment]
Ah that's a good point. We're using hg19 so they are chr1.fa etc.

I've used the [standalone version of CNVnator](https://github.com/abyzovlab/CNVnator) previously with hg19 formatted chromosomes and its worked fine. Perhaps it may be to do with the changes made to the CNVnator-multi program supplied with SpeedSeq?

**Comment by cc2qe** [comment]
yeah, quite possibly the case. It comes down to [this file](https://github.com/hall-lab/speedseq/blob/master/src/cnvnator/src/Genome.cpp) mainly. I think  Alexej may have modified it for more flexibility since the speedseq implementation was written.

**Comment by s-boardman** [comment]
Hi Colby, sorry for the delay.

I've downloaded GRCh37 and set it up as per the user guide. Will be doing some testing over the next few days so shall update this ticket with new information in due course. Hopefully it'll be resolved by the corrected naming as you suspect.

**Comment by s-boardman** [comment]
Hi Colby,

I've been able to run this today and no longer have the chromosome naming error.

However, what we now have is what looks like a root error (output below):

```
/opt/gridware/pkg/apps/speedseq/0.0.3a/gcc-4.4.6+root-5.34.30+samtools-0.1.19+python-2.7.3/bin/cnvnator-multi: error while loading shared libraries: libCore.so.5.34: cannot open shared object file: No such file or directory
```

Should I open a new ticket or do you think this related?

**Comment by cc2qe** [comment]
I think this is a different issue, I've opened a new ticket here https://github.com/hall-lab/speedseq/issues/44

**Comment by s-boardman** [comment]
As per #44;

Command I used to run speedseq sv:

```
qsub -V -e e -o o -cwd -b Y -N speedseq_sv_1 speedseq sv -R /mnt/lustre/references/speedseq/GRCh37/grch37.fasta -o ERR194146 -g -k -d -v \
-B /mnt/archive/analysis/projects/HiSeq/CNV_Genome_Project/External_Data/Illumina_Platinum_Genomes/NA12877/bam_fromfastq_dl/ERR194146.bam \
-S /mnt/archive/analysis/projects/HiSeq/CNV_Genome_Project/External_Data/Illumina_Platinum_Genomes/NA12877/bam_fromfastq_dl/ERR194146.splitters.bam \
-D /mnt/archive/analysis/projects/HiSeq/CNV_Genome_Project/External_Data/Illumina_Platinum_Genomes/NA12877/bam_fromfastq_dl/ERR194146.discordants.bam
```

Error message:

```
Traceback (most recent call last):
  File "/opt/gridware/pkg/apps/speedseq/0.0.3a/gcc-4.4.6+root-5.34.30+samtools-0.1.19+python-2.7.3/bin/cnvnator_wrapper.py", line 350, in <module>
    chroms_list = get_chroms_list(args.bam)
  File "/opt/gridware/pkg/apps/speedseq/0.0.3a/gcc-4.4.6+root-5.34.30+samtools-0.1.19+python-2.7.3/bin/cnvnator_wrapper.py", line 153, in get_chroms_list
    proc = subprocess.Popen(['samtools', 'view', '-H', bam_fn], stdout = subprocess.PIPE)
  File "/opt/gridware/pkg/apps/python/2.7.3/gcc-4.4.6/lib/python2.7/subprocess.py", line 679, in __init__
    errread, errwrite)
  File "/opt/gridware/pkg/apps/python/2.7.3/gcc-4.4.6/lib/python2.7/subprocess.py", line 1249, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

The structure of my references directory is as follows:

```
ls -l /mnt/lustre/references/speedseq/GRCh37/
-rw-rw-r-- 1 sb2 bioinfo 3147288981 Aug 25 14:40 grch37.fasta
-rw-rw-r-- 1 sb2 bioinfo       6563 Aug 26 16:18 grch37.fasta.amb
-rw-rw-r-- 1 sb2 bioinfo        869 Aug 26 16:18 grch37.fasta.ann
-rw-rw-r-- 1 sb2 bioinfo 3095694072 Aug 26 16:17 grch37.fasta.bwt
-rw-rw-r-- 1 sb2 bioinfo        713 Aug 27 13:06 grch37.fasta.fai
-rw-rw-r-- 1 sb2 bioinfo  773923497 Aug 26 16:18 grch37.fasta.pac
-rw-rw-r-- 1 sb2 bioinfo 1547847040 Aug 26 16:30 grch37.fasta.sa

ls -l /mnt/lustre/references/speedseq/annotations/cnvnator_chroms/
-rw-rw-r-- 1 sb2 bioinfo 137793664 Aug 25 13:35 10.fa
-rw-rw-r-- 1 sb2 bioinfo 137256629 Aug 25 13:35 11.fa
-rw-rw-r-- 1 sb2 bioinfo 136082764 Aug 25 13:35 12.fa
-rw-rw-r-- 1 sb2 bioinfo 117089380 Aug 25 13:35 13.fa
-rw-rw-r-- 1 sb2 bioinfo 109138703 Aug 25 13:35 14.fa
-rw-rw-r-- 1 sb2 bioinfo 104240253 Aug 25 13:35 15.fa
-rw-rw-r-- 1 sb2 bioinfo  91860670 Aug 25 13:35 16.fa
-rw-rw-r-- 1 sb2 bioinfo  82548468 Aug 25 13:35 17.fa
-rw-rw-r-- 1 sb2 bioinfo  79378540 Aug 25 13:35 18.fa
-rw-rw-r-- 1 sb2 bioinfo  60114471 Aug 25 13:35 19.fa
-rw-rw-r-- 1 sb2 bioinfo 253404802 Aug 25 13:35 1.fa
-rw-rw-r-- 1 sb2 bioinfo  64075950 Aug 25 13:35 20.fa
-rw-rw-r-- 1 sb2 bioinfo  48932064 Aug 25 13:35 21.fa
-rw-rw-r-- 1 sb2 bioinfo  52159647 Aug 25 13:35 22.fa
-rw-rw-r-- 1 sb2 bioinfo 247252699 Aug 25 13:35 2.fa
-rw-rw-r-- 1 sb2 bioinfo 201322807 Aug 25 13:35 3.fa
-rw-rw-r-- 1 sb2 bioinfo 194340184 Aug 25 13:35 4.fa
-rw-rw-r-- 1 sb2 bioinfo 183930518 Aug 25 13:35 5.fa
-rw-rw-r-- 1 sb2 bioinfo 173966988 Aug 25 13:35 6.fa
-rw-rw-r-- 1 sb2 bioinfo 161790978 Aug 25 13:35 7.fa
-rw-rw-r-- 1 sb2 bioinfo 148803426 Aug 25 13:35 8.fa
-rw-rw-r-- 1 sb2 bioinfo 143566992 Aug 25 13:35 9.fa
-rw-rw---- 1 sb2 bioinfo     16849 Aug 25 14:38 M.fa
-rw-rw---- 1 sb2 bioinfo 157858406 Aug 25 14:36 X.fa
-rw-rw---- 1 sb2 bioinfo  60363129 Aug 25 14:36 Y.fa
```

Is there a key file that I am missing?

**Comment by cc2qe** [comment]
is samtools in your path? also, can you should the header of /mnt/archive/analysis/projects/HiSeq/CNV_Genome_Project/External_Data/Illumina_Platinum_Genomes/NA12877/bam_fromfastq_dl/ERR194146.bam

**Comment by s-boardman** [comment]
Ah, samtools wasn't loaded at the time. It looks like it isn't a linked dependency to speedseq qhen I load that on our cluster.

Here's my bam header for you; chromosome numbering looks fine to me?

```
@HD	VN:1.3	SO:coordinate
@SQ	SN:1	LN:249250621
@SQ	SN:2	LN:243199373
@SQ	SN:3	LN:198022430
@SQ	SN:4	LN:191154276
@SQ	SN:5	LN:180915260
@SQ	SN:6	LN:171115067
@SQ	SN:7	LN:159138663
@SQ	SN:8	LN:146364022
@SQ	SN:9	LN:141213431
@SQ	SN:10	LN:135534747
@SQ	SN:11	LN:135006516
@SQ	SN:12	LN:133851895
@SQ	SN:13	LN:115169878
@SQ	SN:14	LN:107349540
@SQ	SN:15	LN:102531392
@SQ	SN:16	LN:90354753
@SQ	SN:17	LN:81195210
@SQ	SN:18	LN:78077248
@SQ	SN:19	LN:59128983
@SQ	SN:20	LN:63025520
@SQ	SN:21	LN:48129895
@SQ	SN:22	LN:51304566
@SQ	SN:X	LN:155270560
@SQ	SN:Y	LN:59373566
@SQ	SN:M	LN:16569
@RG	ID:ERR194146	SM:ERR194146
@PG	ID:bwa	PN:bwa	CL:/opt/gridware/pkg/apps/bwa/0.7.8/gcc-4.4.6/bin/bwa mem -t 1 -M -R @RG\tID:ERR194146\tSM:ERR194146 /mnt/lustre/references/speedseq/GRCh37/grch37.fasta ../fastq_dl/ERR194146_1.subset.fastq ../fastq_dl/ERR194146_2.subset.fastq	VN:0.7.8-r455
```

**Comment by cc2qe** [comment]
yeah, the samtools thing is an oversight, i didn't realize that it was being called.

BAM header looks fine, is the problem solved if you add samtools to your path?

**Comment by s-boardman** [comment]
Looks OK so far!

I'll be able to check it all on Tuesday (long weekend here in the UK) and hopefully everything will have run hunky dory and I'll be able to close the task for you.

Thanks (again!) for the troubleshooting help. :smile:

**Comment by cc2qe** [comment]
sounds good, appreciate the detailed bug report. i'll change speedseq to explicitly use the embedded sambamba rather than the samtools in PATH

**Comment by s-boardman** [comment]
OK, cool. I've asked our syadmin to pop samtools into the load path for speedseq for the time being so that should make sure I don't see it again.

**Comment by s-boardman** [comment]
Hi Colby, sorry for the late reply.

With samtools in my PATH its worked fine.

I've got an Error (below) which I think is related to me qsubbing the jobs to our cluster via ssh (rather than running speedseq natively). Could you confirm this, and explain what I'm missing out on. This happens with ssh -X (my default) and ssh -Y.

```
Error in <TGClient::TGClient>: can't open display "localhost:11.0", switchingt to batch mode...
 In case you run from a remote ssh session, reconnect with ssh -Y
```

**Comment by cc2qe** [comment]
I also see this error when we submit speedseq jobs through LSF. I'm not sure what CNVnator is attempting to do with X11, but as far as I can tell, you can ignore this message. Does your output complete and look correct?

**Comment by s-boardman** [comment]
Yeah that makes sense. Everything else looked fine so I'm definitely at the
point where it's working as intended.

Thanks for the help again!

**Comment by s-boardman** [comment]
@cc2qe you can mark this issue closed. Following all the helpful comments has resolved the error.
