### ISSUE TITLE
CNVnator ROOT error

### ISSUE THREAD

**Issue by cc2qe** [hall-lab/speedseq#44]
@s-boardman forked from https://github.com/hall-lab/speedseq/issues/40

> Hi Colby,
> 
> I've been able to run this today and no longer have the chromosome naming error.
> 
> However, what we now have is what looks like a root error (output below):
> 
> /opt/gridware/pkg/apps/speedseq/0.0.3a/gcc-4.4.6+root-5.34.30+samtools-0.1.19+python-2.7.3/bin/cnvnator-multi: error while loading shared libraries: libCore.so.5.34: cannot open shared object file: No such file or directory
> Should I open a new ticket or do you think this related?

**Comment by cc2qe** [comment]
It seems like the CNVnator binary is not finding the ROOT libraries. Are you sourcing the ROOT file prior to running  speedseq? It's best to have something like the following in the speedseq.config file:
```
source /gsc/pkg/root/root/bin/thisroot.sh
```

Then just run cnvnator-multi to make sure it's working properly before running speedseq:
```
$ /opt/gridware/pkg/apps/speedseq/0.0.3a/gcc-4.4.6+root-5.34.30+samtools-0.1.19+python-2.7.3/bin/cnvnator-multi
Not enough parameters.

CNVnator v0.3

Usage:
/gscmnt/gc2719/halllab/users/cchiang/src/speedseq/bin/cnvnator-multi -root out.root  [-genome name] [-chrom 1 2 ...] -tree  file1.bam ...
/gscmnt/gc2719/halllab/users/cchiang/src/speedseq/bin/cnvnator-multi -root out.root  [-genome name] [-chrom 1 2 ...] [-nthreads threads] -ptree  file1.bam ...
/gscmnt/gc2719/halllab/users/cchiang/src/speedseq/bin/cnvnator-multi -root out.root  [-genome name] [-chrom 1 2 ...] -merge file1.root ...
/gscmnt/gc2719/halllab/users/cchiang/src/speedseq/bin/cnvnator-multi -root file.root [-genome name] [-chrom 1 2 ...] [-d dir] -his bin_size
/gscmnt/gc2719/halllab/users/cchiang/src/speedseq/bin/cnvnator-multi -root file.root [-chrom 1 2 ...] -stat      bin_size
/gscmnt/gc2719/halllab/users/cchiang/src/speedseq/bin/cnvnator-multi -root file.root                  -eval      bin_size
/gscmnt/gc2719/halllab/users/cchiang/src/speedseq/bin/cnvnator-multi -root file.root [-chrom 1 2 ...] -partition bin_size [-ngc]
/gscmnt/gc2719/halllab/users/cchiang/src/speedseq/bin/cnvnator-multi -root file.root [-chrom 1 2 ...] -call      bin_size [-ngc]
/gscmnt/gc2719/halllab/users/cchiang/src/speedseq/bin/cnvnator-multi -root file.root -genotype bin_size [-ngc]
/gscmnt/gc2719/halllab/users/cchiang/src/speedseq/bin/cnvnator-multi -root file.root -view     bin_size [-ngc]
/gscmnt/gc2719/halllab/users/cchiang/src/speedseq/bin/cnvnator-multi -pe   file1.bam ... -qual val(20) -over val(0.8) [-f file]

Valid genomes (-genome option) are: NCBI36, hg18, GRCh37, hg19
```

**Comment by s-boardman** [comment]
Ah yes, I can see the path to `thisroot.sh` isn't setup correctly.

I'll have to get our syadmin to sort it. Will update you in due course once it's fixed to confirm this was indeed the issue.

Thanks for the help. :)

**Comment by s-boardman** [comment]
Our sysadmin has managed to rectify it; I get the correct usage when running `/opt/gridware/pkg/apps/speedseq/0.0.3a/gcc-4.4.6+root-5.34.30+samtools-0.1.19+python-2.7.3/bin/cnvnator-multi`.

However, now I'm back with the same problem as #40. Could you reopen that one? I'll add some more info to it rather than this one for clarity.

**Comment by cc2qe** [comment]
ok, good I;m closing this and reopening the other issue
