### ISSUE TITLE
Variant calling fails with [ti_index_core] the chromosome blocks not continuous

### ISSUE THREAD

**Issue by jvolanen** [hall-lab/speedseq#53]
*speedseq somatic -v* fails with following output:

    Calling somatic variants...

        create temporary directory

        /opt/speedseq//bin/freebayes -f /opt/vcp_files/human_g1k_v37.fasta \
            --pooled-discrete \
            --min-repeat-entropy 1 \
            --genotype-qualities \
            --min-alternate-fraction 0.05 \
            --min-alternate-count 2 \
            --region $chrom:$start..$end \
            /bamdir/126_normal.bam /bamdir/126_1.bam \
            | somatic_filter 10 18 0 \
            > /workdir/126_1.$chrom:$start..$end.vcf

        cat /workdir/var_command.txt | /opt/speedseq//bin/parallel -j 32

        grep "^##" /workdir/126_1.MT:12136..12498.vcf \
        | cat - <(echo '##INFO=<ID=SSC,Number=1,Type=Float,Description="Somatic score">') <(grep "^#CHROM" /workdir/126_1.MT:12136..12498.vcf) > /workdir/header.txt

        cat /workdir/126_1."$chrom:$start..$end".vcf | grep -v "^#" \
            | sort -k1,1 -k2,2n | cat /workdir/header.txt - \
            | /opt/speedseq//bin/bgzip -c > /workdir/126_1.vcf.gz

        /opt/speedseq//bin/tabix -f -p vcf /workdir/126_1.vcf.gz 
    [ti_index_core] the chromosome blocks not continuous at line 1567, is the file sorted? [pos12247310]

The vcf file is indeed not correctly sorted. The problem seems to be related locale settings: 

    $ env | grep LANG
    LANG=en_US.UTF-8
    $ sort --help
    <snip>
     *** WARNING ***
    The locale specified by the environment affects sort order.
    Set LC_ALL=C to get the traditional sort order that uses
    native byte values.
    <snip>

I suggest setting *LC_ALL=C* in SpeedSeq to avoid issues with different locale settings.

**Comment by cc2qe** [comment]
thanks for the report, I can't actually replicate the error on my system, but have added LC_ALL=C with https://github.com/hall-lab/speedseq/commit/a95704a25d1f6b5dc65489a1e38b2b734215f97f, so hopefully that fixes it
