### ISSUE TITLE
speedseq align error

### ISSUE THREAD

**Issue by kongdeju** [hall-lab/speedseq#55]
[M::mem_pestat] skip orientation RF
[M::mem_process_seqs] Processed 640000 reads in 121.103 CPU sec, 15.293 real sec
/bin/bash: line 1: 27583 Broken pipe             /expan/programs/speed/speedseq//bin/bwa mem -t 8 -R '@RG\tID:1502\tSM:1502\tLB:lib1' /expan/programs/fastq2vcf/hg19/hg19.fa 1502_L3_7002.R1.clean.fastq.gz 1502_L3_7002.R2.clean.fastq.gz
     27584                       | /expan/programs/speed/speedseq//bin/samblaster --excludeDups --addMateTags --maxSplitCount 2 --minNonOverlap 20 --splitterFile 1502_8.kk11RkV0pxsv/spl_pipe --discordantFile 1502_8.kk11RkV0pxsv/disc_pipe
     27585                       | /expan/programs/speed/speedseq//bin/sambamba view -S -f bam -l 0 /dev/stdin
     27586 Killed                  | /expan/programs/speed/spee

broken pipe ,why?

**Comment by cc2qe** [comment]
Can you please post your command (using the "-v" verbose option) as well as the output?

Some questions:
- How long before this error occurs?
- Does your filesystem support named pipes (i.e. can you do `mkfifo test`)?
- Do you have enough disk space to write the BAM output?
- Do you have enough RAM to run BWA?
- is your reference fasta indexed with BWA MEM?

**Comment by kongdeju** [comment]
Thank you very much for your reply.      This is running command.
       /expan/programs/speed/speedseq/bin/speedseq align \
       -o 1502_8 \
       -t 8 \
       -M 10
        -R "@RG\tID:1502\tSM:1502\tLB:lib1" \
              /expan/programs/fastq2vcf/hg19/hg19.fa \
            1502_L3_7002.R1.clean.fastq.gz \
            1502_L3_7002.R2.clean.fastq.gz
    it would run about one hour,then this error,occured. I have tested this for several times.
    Yes, My filesystem support pipes.
    I have about 200G spare space, and fastq.gz file is about 10G 
    The RAM of is 20G large and i have 8 cores.
    The reference is indexed with bwa mem

when i tried to run speedseq on a small fastq.gz files , this kind of error dispeared.

**Comment by cc2qe** [comment]
this seems like a memory issue, you will need ~32 GB of memory for a human 50X alignment with default parameters.

I would reduce the "-M" parameter to 3 (the minimum) and try running it again to see if 20 GB RAM is enough
