### ISSUE TITLE
How to use speedseq somatic

### ISSUE THREAD

**Issue by bioxu** [hall-lab/speedseq#57]
Hi,all
I am beginer with SpeedSeq.I have 40 cancer-normal WGS and want to call somatic snps,but I don't konw how to use speedseq somatic exactly.
1.How to create a tumor or normal bam file from 40 WGS data,respectively.
2.GRCh37 is the necessary genome reference fasta file? Can I use h19?

@cc2qe expect your reply.

**Comment by cc2qe** [comment]
here is an example workflow for each tumor normal pair: https://github.com/hall-lab/speedseq#call-variants-on-a-tumornormal-pair

It's better to use GRCh37 than hg19, because some of the downstream steps (CNVnator for structural variation detection) cannot handle chromosome prefixes

**Comment by bioxu** [comment]
Dear cc2qe,
Thanks for your reply. you know I'm a beginer to call somatic snp,so I have these question:
1. Should I call somatic snp for each tumor normal pair use speedseq-somatic?If yes, what should I do to integrate these somatic files?(I have 40 samples)
2. If I completely call somatic,annotation is next work,I had used Annovar,I want to know if I can use this tool to substitute the VEP?
Thanks.
