### ISSUE TITLE
Specifying VEP cache build

### ISSUE THREAD

**Issue by vasiliosz** [hall-lab/speedseq#63]
Hi, 

Is it possible to pass the `--assembly` flag to VEP through speedseq? 
My VEP cache dir contains both GRCh37 and GRCh38 and thus requires a build specification. 

An example of the error when running `speedseq sv` with the `-A` flag: 
```
LUMPY Express done
ERROR: Multiple assemblies found for cache version 82 (GRCh37, GRCh38) - specify one using --assembly [assembly]
[ti_index_core] the file out of order at line 8
```

**Comment by cc2qe** [comment]
https://github.com/hall-lab/speedseq/commit/0eab42ec64d701d18b930ba48b9f488e27eb407b should hep

**Comment by vasiliosz** [comment]
Many thanks!
