### ISSUE TITLE
sambamba-view: [zlib] unknown error;  not enough data in stream

### ISSUE THREAD

**Issue by stephenrdoyle** [hall-lab/speedseq#64]
Hi, 

Testing out speedseq on a non-human/non-model dataset and I am getting the following error:

sambamba-view: [zlib] unknown error
sambamba-sort: not enough data in stream
sambamba-view: [zlib] unknown error
sambamba-sort: not enough data in stream

Any thoughts would be greatly appreciated.
Cheers, 
S

**Comment by avilella** [comment]
This is an issue in sambamba:

https://github.com/lomereiter/sambamba/issues/178

**Comment by cc2qe** [comment]
This should be fixed in e99d565079ebc12a1745efc27c973156009caa3d
