### ISSUE TITLE
Parameter required for ID. 

### ISSUE THREAD

**Issue by rmande** [hall-lab/speedseq#72]
I am trying to run speedseq sv on a trio of bam files and I am getting an error "Parameter required for id".  I've tried to look at possible solutions online but there don't seem to be any.  Do you know why I might be getting this error and how I could potentially fix it?

**Comment by cc2qe** [comment]
do your BAM files have readgroup information?

**Comment by rmande** [comment]
How do I check?

**Comment by cc2qe** [comment]
samtools view -H <my.bam>

**Comment by rmande** [comment]
I have one @RG tag per bam file.  Is that normal?

**Comment by rmande** [comment]
Just double checking, 
Is one @RG tag normal?

**Comment by cc2qe** [comment]
It's ok to just have one per BAM, but your RG tag should include, SM (sample) ID (identification), and LB (library) information. If it does not then speedseq probably will not run properly.

also, if you generated your BAM files outside of the speedseq pipeline, then they might not be compatible with SV detection
