### ISSUE TITLE
could speedseq run WES or Panel with other Bed files 

### ISSUE THREAD

**Issue by yipukangda** [hall-lab/speedseq#78]
hi,
I want to use speedseq to run some wes or panel samples, is it OK to use other bed files instead of its own bed file "ceph18.b37.include.2014-01-15.bed"?(it seems too slow to use its own bed file)

thanks

**Comment by cc2qe** [comment]
certainly, you can use any bed file you'd like (or none at all) for `speedseq var` and it shouldn't affect downstream analyses
