### ISSUE TITLE
speedseq waits indefinitely?

### ISSUE THREAD

**Issue by ekg** [hall-lab/speedseq#8]
I am trying to speeseq aln, and although it appears I have all the prerequisites installed the process just sits there at 0% CPU indefinitely.

Here are my inputs: (http://clavius.bc.edu/~erik/speedseq/)
http://clavius.bc.edu/~erik/speedseq/chr20_bit.fa
http://clavius.bc.edu/~erik/speedseq/sample005.fa_1.fastq
http://clavius.bc.edu/~erik/speedseq/sample005.fa_2.fastq

Please let me know what obvious thing I'm doing wrong :)

**Comment by cc2qe** [comment]
going to close this because the code and installation has changed substantially since then
