### ISSUE TITLE
somatic VEP missing variants on X (and Y etc.)

### ISSUE THREAD

**Issue by mcieslik-mctp** [hall-lab/speedseq#81]
I noticed that if I run speedseq somatic with the (-A) option enabled the final vcf file does not contain variants on chromosomes other than 1:22, the variants are there if speedseq is run without (-A), they are also present in the temporary Freebayes output. I use the default "include" file and all parameters default. 

After some debugging I found that there is an issue with VEP, but actually the bug is in speedseq.

VEP allows results to be written to stdout by specifying '-o STDOUT' speedseq uses '-o /dev/stdout' this means that VEP thinks that /dev/stdout is a regular file and if it runs into any warnings it will try to write "/dev/stdout_warnings.txt" which of course is forbidden. A warning will occur if VEP runs into a chromosome that it doesn't know (such as the GL_*), this results in a silent error of writing to /dev/stdout_warnings.txt and all variants on GL_*, X, Y, MT etc will be lost.

The solution is to change '-o /dev/stdout' to '-o STDOUT'

**Comment by cc2qe** [comment]
Thanks for bringing this to our attention, I've patched it with the solution that you suggested
