### ISSUE TITLE
RG not retained using realign

### ISSUE THREAD

**Issue by jujubix** [hall-lab/speedseq#82]
Realigning a BAM file with 3 read groups (lanes) using speedseq realign with default settings (no -R option).  RG information is correctly parsed out of the original header and put into the realigned BAM, but the RG tag is not propagated to the final BAMs.

Tracing the run back, it looks like bamtofastq is correctly pulling the RG tag out and putting it as a FASTQ comment, but the bwa mem run is NOT using the -C option to append this RG:Z tag to the end of the SAM output.

Looking into speedseq, it looks like the problem is here starting at line 1856:
````
# if user supplies command line readgroup info, then override existing RG info in input BAMs
if [[ -z $RG_FMT ]]
then
RETAIN_INPUT_RG=""
else
RETAIN_INPUT_RG="-C"
fi
````

Shouldn't it be `! -z $RG_FMT` instead?  That is to say, with the -R it not used (my situation), -R will be empty, in which case the -C SHOULD be set, so bwa mem will append the RG:Z tag in the FASTQ comment to bwa mem output?

**Comment by cc2qe** [comment]
thanks for bringing this to my attention, you're correct and I've patched the code to fix this
