### ISSUE TITLE
variant calls using exome?

### ISSUE THREAD

**Issue by wisekh6** [hall-lab/speedseq#94]
Hello,

I wonder if speedseq can also use Exome data to call variants. I believe speedseq would not have restriction to DNA data type, but I would like to have confirmation from the speedseq author.

thank you,

HK

**Comment by cc2qe** [comment]
yes, SpeedSeq should work fine on exome data for SNP and indel variant calling. just don't use the [excluded regions](https://github.com/hall-lab/speedseq#annotations)

You will not be able to call SVs however

**Comment by ieiwk** [comment]
hi, why not using the excluded regions?
